server:
  port: 8889

spring:
  application:
    name: api-gateway

jwt:
  secret: whiskerguard-jwt-secret

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: whiskerguard
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: org-service
          uri: lb://organization-service
          predicates:
            - Path=/org/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: orgCircuit
                fallbackUri: forward:/fallback/org
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuit
                fallbackUri: forward:/fallback/auth

    loadbalancer:
      ribbon:
        enabled: false

  #redis:
  #  host: localhost
  #  port: 6379

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

