
spring.config.import-check.enabled: false

server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: whiskerguard
      config:
        server-addr: localhost:8848  # Nacos 地址
        file-extension: yml
        namespace: whiskerguard  # Nacos 的命名空间
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/yanhaishui/whiskerguard-config
          search-paths: config
          clone-on-start: true
          default-label: main
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
